name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup and cache
        uses: ./.github/actions/setup-and-cache

      - name: Install dependencies
        run: pnpm install

      - name: Run lint
        run: pnpm run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup and cache
        uses: ./.github/actions/setup-and-cache

      - name: Install dependencies
        run: pnpm install

      - name: Run build
        run: pnpm run build

      - name: Run typecheck
        run: pnpm run typecheck

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 8

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup and cache
        uses: ./.github/actions/setup-and-cache

      - name: Install dependencies
        run: pnpm install

      - name: Run build
        run: pnpm run build

      - name: Run test
        run: pnpm run test
