name: Version PR
on:
  push:
    tags:
      - 'v*'

jobs:
  version:
    runs-on: ubuntu-latest
    timeout-minutes: 8

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
          run_install: false

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Create version PR
        id: changeset_version_pr
        uses: changesets/action@v1
        with:
          commit: "chore(version): version packages"
          title: "chore(version): version packages"
          version: pnpm ci:version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
